on:
  push:
    branches:
      - 'master'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      volumes:
        - android-app-keystore:/keystore
    steps:
      - name: Fix Permissions
        run: |
          echo "Fixing permissions for workspace..."
          apt update
          apt upgrade -y
          apt install -y unzip openjdk-17-jdk
          whoami
          su root
          chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Submodules
        run: |
          echo "Updating submodules..."
          git submodule update --init

      - name: Generate Keystore File
        run: |
          echo "Generating keystore file..."
          keytool -genkey -v -keystore $GITHUB_WORKSPACE/my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass my-store-password -keypass my-key-password -alias my-key -dname "CN=Example, OU=Example, O=Example, L=City, S=State, C=US"

      - name: Decode Secret Signing Configuration
        run: |
          echo "Decoding secret signing configuration..."
          echo ${{ secrets.OPENEUICC_SIGNING_CONFIG }} | base64 --decode > $GITHUB_WORKSPACE/keystore.properties

      - name: Ensure keystore.properties Exists
        run: |
          echo "Ensuring keystore.properties exists..."
          if [ ! -f "$GITHUB_WORKSPACE/keystore.properties" ]; then
            echo "storePassword=my-store-password" > $GITHUB_WORKSPACE/keystore.properties
            echo "keyPassword=my-key-password" >> $GITHUB_WORKSPACE/keystore.properties
            echo "keyAlias=my-key" >> $GITHUB_WORKSPACE/keystore.properties
            echo "unprivKeyPassword=my-unpriv-password" >> $GITHUB_WORKSPACE/keystore.properties
            echo "unprivKeyAlias=my-unpriv-key" >> $GITHUB_WORKSPACE/keystore.properties
            echo "storeFile=$GITHUB_WORKSPACE/my-release-key.jks" >> $GITHUB_WORKSPACE/keystore.properties
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk-version: 25.1.8937393

      - name: Build Privileged OpenEUICC APK
        run: |
          echo "Building privileged OpenEUICC APK..."
          ./gradlew :app:assembleRelease

      - name: Build EasyEUICC APK
        run: |
          echo "Building EasyEUICC APK..."
          ./gradlew :app-unpriv:assembleRelease

      - name: Copy Artifacts
        run: |
          echo "Copying artifacts..."
          find . -name 'app*-release.apk' -exec cp {} . \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release APKs
          path: app*-release.apk
