on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      volumes:
        - android-app-keystore:/keystore
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - name: Fix Permissions
        run: |
          echo "Fixing permissions for workspace..."
          whoami
          su root
          chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Decode Secret Signing Configuration
        run: |
          echo "Decoding secret signing configuration..."
          echo ${{ secrets.OPENEUICC_SIGNING_CONFIG }} | base64 --decode > $GITHUB_WORKSPACE/keystore.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk-version: 25.1.8937393

      - name: Build Release APK (Unprivileged / EasyEUICC only)
        run: |
          echo "Building release APK for EasyEUICC..."
          ./gradlew --no-daemon :app-unpriv:assembleRelease

      - name: Copy Debug Symbols to Release Path
        run: |
          echo "Copying debug symbols to release path..."
          cp app-unpriv/build/outputs/native-debug-symbols/release/native-debug-symbols.zip app-unpriv/build/outputs/apk/release/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Release notes will be updated manually."
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-unpriv/build/outputs/apk/release/native-debug-symbols.zip
          asset_name: native-debug-symbols.zip
          asset_content_type: application/zip
